//------------------------------------------------------------------------------
// <auto-generated>
//     Tento kód byl generován nástrojem.
//     Verze modulu runtime:4.0.30319.42000
//
//     Změny tohoto souboru mohou způsobit nesprávné chování a budou ztraceny,
//     dojde-li k novému generování kódu.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LauncherFix.Properties {
    using System;
    
    
    /// <summary>
    ///   Třída prostředků se silnými typy pro vyhledávání lokalizovaných řetězců atp.
    /// </summary>
    // Tato třída byla automaticky generována třídou StronglyTypedResourceBuilder
    // pomocí nástroje podobného aplikaci ResGen nebo Visual Studio.
    // Chcete-li přidat nebo odebrat člena, upravte souboru .ResX a pak znovu spusťte aplikaci ResGen
    // s parametrem /str nebo znovu sestavte projekt aplikace Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Vrací instanci ResourceManager uloženou v mezipaměti použitou touto třídou.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LauncherFix.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Potlačí vlastnost CurrentUICulture aktuálního vlákna pro všechna
        ///   vyhledání prostředků pomocí třídy prostředků se silnými typy.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _9778cf761c8d4fb5975aeb33706c0721 {
            get {
                object obj = ResourceManager.GetObject("9778cf761c8d4fb5975aeb33706c0721", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Close launcher on application launch.
        /// </summary>
        internal static string CloseLauncherOnAPPStartMSG {
            get {
                return ResourceManager.GetString("CloseLauncherOnAPPStartMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Discover a powerful yet intuitive application designed to empower you. Effortlessly generate EVM-compatible cryptocurrency smart contracts, complete with customizable features like transfer fees. Alternatively, build your own on-chain MoveVM databases for diverse applications, from personal data management to secure, decentralized storage of any type of information..
        /// </summary>
        internal static string codeapp {
            get {
                return ResourceManager.GetString("codeapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Confirm.
        /// </summary>
        internal static string ConfirmMSG {
            get {
                return ResourceManager.GetString("ConfirmMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Launch.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledává lokalizovaný prostředek typu System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap qweqwe {
            get {
                object obj = ResourceManager.GetObject("qweqwe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Choose color scheme .
        /// </summary>
        internal static string SelectColorSchemeMainMSG {
            get {
                return ResourceManager.GetString("SelectColorSchemeMainMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Choose color scheme (secondary).
        /// </summary>
        internal static string SelectColorSchemeSecondaryMSG {
            get {
                return ResourceManager.GetString("SelectColorSchemeSecondaryMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Select language.
        /// </summary>
        internal static string SelectLanguageMSG {
            get {
                return ResourceManager.GetString("SelectLanguageMSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Vyhledá lokalizovaný řetězec podobný Interested in trading digital assets? Create your own Grid or DCA trading strategy and start live-testing it immediately. Our specially optimized platform allows for full customization — from entry parameters to risk management — so you can tailor every detail to your needs. Take full control of your trades and unlock the full potential of automation. All of this is easy, fast, and completely free..
        /// </summary>
        internal static string tradingapp {
            get {
                return ResourceManager.GetString("tradingapp", resourceCulture);
            }
        }
    }
}
